(provide display-transaction display-transactions)

(require "lima/types.scm")
(require "lima/import/types.scm")

(define (indent) (display "  "))

(define (display-transaction txn)
  (display (transaction-date txn))
  (display " ")
  (display "txn")
  (display " \"")
  (display (transaction-payee txn))
  (display "\"")
  (displayln)
  (indent)
  (display (transaction-base-account txn))
  (display "  ")
  (let ((amt (transaction-amount txn)))
    (display (amount-number amt))
    (display " ")
    (display (amount-currency amt)))
  (displayln)
  (for-each (lambda (acc)
             (indent)
             (display acc)
             (displayln))
    (transaction-other-accounts txn))
  (displayln))

(define (display-transactions txns)
  (for-each display-transaction txns))
