(require "steel/tests/unit-test.scm"
  (for-syntax "steel/tests/unit-test.scm"))

(require "lima/types.scm")
(require "lima/import/pairing.scm")

(test-module
  "is-pair? tests"
  (check-equal? "is-pair? one account"
    (is-pair? `((amount . ,(amount (decimal -350 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "B") (infer-count . 1) (infer-category . "payee"))))
                (txnid . "t2"))
      `((amount . ,(amount (decimal 350 2) "NZD"))
        (primary-account . "B")
        (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
        (txnid . "t1")))
    #t)
  (check-equal? "try-pair different amount"
    (is-pair? `((amount . ,(amount (decimal -450 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "B") (infer-count . 1) (infer-category . "payee"))))
                (txnid . "t2"))
      `((amount . ,(amount (decimal 350 2) "NZD"))
        (primary-account . "B")
        (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
        (txnid . "t1")))
    #f))

(test-module
  "try-pair tests"
  (check-equal? "try-pair one account success"
    (try-pair `((amount . ,(amount (decimal -350 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "B") (infer-count . 1) (infer-category . "payee"))))
                (txnid . "t2"))
      `(((amount . ,(amount (decimal 350 2) "NZD"))
         (primary-account . "B")
         (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
         (txnid . "t1"))))
    `(((txnid2 . "t2")
       (amount . ,(amount (decimal 350 2) "NZD"))
       (primary-account . "B")
       (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
       (txnid . "t1"))))
  (check-equal? "try-pair one account success but no txnid"
    (try-pair `((amount . ,(amount (decimal -350 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "B") (infer-count . 1) (infer-category . "payee")))))
      `(((amount . ,(amount (decimal 350 2) "NZD"))
         (primary-account . "B")
         (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
         (txnid . "t1"))))
    `(((comment . "paired with \"\" \"\"")
       (amount . ,(amount (decimal 350 2) "NZD"))
       (primary-account . "B")
       (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
       (txnid . "t1"))))
  (check-equal? "try-pair amount mismatch"
    (try-pair `((amount . ,(amount (decimal -450 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "B") (infer-count . 1) (infer-category . "payee"))))
                (txnid . "t2"))
      `(((amount . ,(amount (decimal 350 2) "NZD"))
         (primary-account . "B")
         (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
         (txnid . "t1"))))
    #f)
  (check-equal? "try-pair account mismatch"
    (try-pair `((amount . ,(amount (decimal -450 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "C") (infer-count . 1) (infer-category . "payee"))))
                (txnid . "t2"))
      `(((amount . ,(amount (decimal 350 2) "NZD"))
         (primary-account . "B")
         (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
         (txnid . "t1"))))
    #f)
  (check-equal? "try-pair multiple accounts"
    (try-pair `((amount . ,(amount (decimal -450 2) "NZD"))
                (primary-account . "A")
                (secondary-accounts . (((name . "B") (infer-count . 1) (infer-category . "payee"))
                                       ((name . "C") (infer-count . 1) (infer-category . "payee"))))
                (txnid . "t2"))
      `(((amount . ,(amount (decimal 350 2) "NZD"))
         (primary-account . "B")
         (secondary-accounts . (((name . "A") (infer-count . 1) (infer-category . "payee"))))
         (txnid . "t1"))))
    #f))
