[package]
name = "beancount-lima-booking"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = { workspace = true, optional = true }
hashbrown = { workspace = true }

[features]
default = ["rust_decimal"]
rust_decimal = ["dep:rust_decimal"]
